steps:
  - label: "update docker image"
    command: "docker pull jamesdbloom/mockserver:maven"

  - wait

  - label: "build"
    command: "docker run -v /var/lib/buildkite-agent/builds/$BUILDKITE_AGENT_NAME/mockserver:/build -w /build/mockserver -a stdout -a stderr -e BUILDKITE_BRANCH=$BUILDKITE_BRANCH jamesdbloom/mockserver:maven /build/mockserver/scripts/buildkite_deploy_snapshot.sh"
