{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mockserver.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "mockserver.name" . }}
    chart: {{ template "mockserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if .Values.letsEncrypt.enabled }}
      certmanager.k8s.io/issuer: {{ template "mockserver.name" . }}
    {{- end -}}
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  {{- if .Values.letsEncrypt.enabled }}
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . }}
      {{- end }}
      secretName: tls-{{ template "mockserver.name" . }}-ingress
  {{- end }}
  {{- if .Values.ingress.tls }}
    {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: serviceport
  {{- end }}
{{- end }}
