replicaCount: 1

app:
  logLevel: "INFO"
  serverPort: "1080"

image:
  repository: jamesdbloom
  snapshot: false
  pullPolicy: IfNotPresent

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: NodePort
  port: 1080
  nodePort: ""

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - mockserver.local

podAnnotations: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

letsEncrypt:
  enabled: false
  ### Select LetsEncrypt environment by uncommenting out the respective line
  ## LetsEncrypt Production:
  server: https://acme-v02.api.letsencrypt.org/directory
  ## LetsEncrypt Staging:
  #server: https://acme-staging-v02.api.letsencrypt.org/directory
  ### Set your email address to be included in the certificate request
  email: test@test.com
